# -*- coding: utf-8 -*-
"""stream.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pyo3ZRngc_tw2rD7Ao3chtvm6NVOQTEw
"""

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
 %%writefile app.py
 import streamlit as st
 st.write('#Waddup')
 st.write('##welcome')
