# -*- coding: utf-8 -*-
"""stream.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pyo3ZRngc_tw2rD7Ao3chtvm6NVOQTEw
"""

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# st.write('#Waddup')
# st.write('##welcome')

#!pip install pyngrok

#from pyngrok import ngrok

#ngrok.set_auth_token("2Ug6eSg3J0CrfTh1uil95P25Icm_7qdcXeCqpqxYzoryWF1qN")

#$ngrok config add-authtoken 2Ug6eSg3J0CrfTh1uil95P25Icm_7qdcXeCqpqxYzoryWF1qN

#!nohup streamlit run app.py --server.port 80 &
#url = ngrok.connect(port = '80')
#print(url)